package net.migats21.interactiveeye.util;

import com.google.common.collect.Maps;
import io.netty.util.Attribute;
import net.minecraft.world.level.material.Material;
import net.minecraft.world.level.material.MaterialColor;

import java.util.HashMap;
import java.util.Map;

public class StringMappings {
    public static Map<Material, String> materials;
    public static Map<MaterialColor, String> materialColors;

    public static void init() {
        materials = Maps.newHashMap();
        materials.put(Material.AIR,"air");
        materials.put(Material.AMETHYST,"amethyst");
        materials.put(Material.BAMBOO,"bamboo");
        materials.put(Material.BARRIER,"static");
        materials.put(Material.BAMBOO_SAPLING,"bamboo");
        materials.put(Material.BUBBLE_COLUMN,"water");
        materials.put(Material.BUILDABLE_GLASS,"glass");
        materials.put(Material.CACTUS,"cactus");
        materials.put(Material.CAKE,"cake");
        materials.put(Material.CLAY,"clay");
        materials.put(Material.CLOTH_DECORATION,"wool");
        materials.put(Material.DECORATION,"decoration");
        materials.put(Material.DIRT,"dirt");
        materials.put(Material.EGG,"egg");
        materials.put(Material.EXPLOSIVE,"explosive");
        materials.put(Material.FIRE,"fire");
        materials.put(Material.FROGLIGHT,"froglight");
        materials.put(Material.FROGSPAWN,"frog spawn");
        materials.put(Material.GLASS,"glass");
        materials.put(Material.GRASS,"grass");
        materials.put(Material.ICE,"ice");
        materials.put(Material.ICE_SOLID,"ice");
        materials.put(Material.LAVA,"lava");
        materials.put(Material.LEAVES,"leaves");
        materials.put(Material.METAL,"metal");
        materials.put(Material.MOSS,"moss");
        materials.put(Material.NETHER_WOOD,"nether_wood");
        materials.put(Material.PISTON,"piston");
        materials.put(Material.PLANT,"plant");
        materials.put(Material.PORTAL,"portal");
        materials.put(Material.POWDER_SNOW,"snow");
        materials.put(Material.REPLACEABLE_PLANT,"plant");
        materials.put(Material.REPLACEABLE_FIREPROOF_PLANT,"plant");
        materials.put(Material.REPLACEABLE_WATER_PLANT,"water_plant");
        materials.put(Material.SAND,"sand");
        materials.put(Material.SCULK,"sculk");
        materials.put(Material.SHULKER_SHELL,"shulker_box");
        materials.put(Material.SNOW,"snow");
        materials.put(Material.SPONGE,"sponge");
        materials.put(Material.STONE,"stone");
        materials.put(Material.STRUCTURAL_AIR,"static");
        materials.put(Material.TOP_SNOW,"snow");
        materials.put(Material.VEGETABLE,"vegetable");
        materials.put(Material.WATER,"water");
        materials.put(Material.WATER_PLANT,"water_plant");
        materials.put(Material.WEB,"cobweb");
        materials.put(Material.WOOD,"wood");
        materials.put(Material.WOOL,"wool");

        materialColors = Maps.newHashMap();
        materialColors.put(MaterialColor.CLAY, "clay");
        materialColors.put(MaterialColor.COLOR_BLACK, "black");
        materialColors.put(MaterialColor.COLOR_BLUE, "blue");
        materialColors.put(MaterialColor.COLOR_BROWN, "brown");
        materialColors.put(MaterialColor.COLOR_CYAN, "cyan");
        materialColors.put(MaterialColor.COLOR_GRAY, "gray");
        materialColors.put(MaterialColor.COLOR_GREEN, "black");
        materialColors.put(MaterialColor.COLOR_LIGHT_BLUE, "light_blue");
        materialColors.put(MaterialColor.COLOR_LIGHT_GRAY, "light_gray");
        materialColors.put(MaterialColor.COLOR_LIGHT_GREEN, "light_green");
        materialColors.put(MaterialColor.COLOR_MAGENTA, "magenta");
        materialColors.put(MaterialColor.COLOR_ORANGE, "orange");
        materialColors.put(MaterialColor.COLOR_PINK, "pink");
        materialColors.put(MaterialColor.COLOR_PURPLE, "purple");
        materialColors.put(MaterialColor.COLOR_RED, "red");
        materialColors.put(MaterialColor.COLOR_YELLOW, "yellow");
        materialColors.put(MaterialColor.CRIMSON_HYPHAE, "crimson_hyphae");
        materialColors.put(MaterialColor.CRIMSON_NYLIUM, "crimson_nylium");
        materialColors.put(MaterialColor.CRIMSON_STEM, "crimson_wood");
        materialColors.put(MaterialColor.DEEPSLATE, "deepslate");
        materialColors.put(MaterialColor.DIAMOND, "diamond");
        materialColors.put(MaterialColor.DIRT, "dirt");
        materialColors.put(MaterialColor.EMERALD, "emerald");
        materialColors.put(MaterialColor.FIRE, "fire");
        materialColors.put(MaterialColor.GLOW_LICHEN, "glow_lichen");
        materialColors.put(MaterialColor.GOLD, "gold");
        materialColors.put(MaterialColor.GRASS, "grass");
        materialColors.put(MaterialColor.ICE, "ice");
        materialColors.put(MaterialColor.LAPIS, "lapis");
        materialColors.put(MaterialColor.METAL, "metalic");
        materialColors.put(MaterialColor.NETHER, "nether");
        materialColors.put(MaterialColor.NONE, "transparent");
        materialColors.put(MaterialColor.PLANT, "plant");
        materialColors.put(MaterialColor.PODZOL, "podzol");
        materialColors.put(MaterialColor.QUARTZ, "quartz");
        materialColors.put(MaterialColor.RAW_IRON, "raw_iron");
        materialColors.put(MaterialColor.SAND, "sand");
        materialColors.put(MaterialColor.SNOW, "snow");
        materialColors.put(MaterialColor.STONE, "stone");
        materialColors.put(MaterialColor.TERRACOTTA_BLACK, "terracotta_black");
        materialColors.put(MaterialColor.TERRACOTTA_BLUE, "terracotta_blue");
        materialColors.put(MaterialColor.TERRACOTTA_BROWN, "terracotta_brown");
        materialColors.put(MaterialColor.TERRACOTTA_CYAN, "terracotta_cyan");
        materialColors.put(MaterialColor.TERRACOTTA_GRAY, "terracotta_gray");
        materialColors.put(MaterialColor.TERRACOTTA_GREEN, "terracotta_green");
        materialColors.put(MaterialColor.TERRACOTTA_LIGHT_BLUE, "terracotta_light_blue");
        materialColors.put(MaterialColor.TERRACOTTA_LIGHT_GRAY, "terracotta_light_gray");
        materialColors.put(MaterialColor.TERRACOTTA_LIGHT_GREEN, "terracotta_light_green");
        materialColors.put(MaterialColor.TERRACOTTA_MAGENTA, "terracotta_magenta");
        materialColors.put(MaterialColor.TERRACOTTA_ORANGE, "terracotta_orange");
        materialColors.put(MaterialColor.TERRACOTTA_PINK, "terracotta_pink");
        materialColors.put(MaterialColor.TERRACOTTA_PURPLE, "terracotta_purple");
        materialColors.put(MaterialColor.TERRACOTTA_RED, "terracotta_red");
        materialColors.put(MaterialColor.TERRACOTTA_WHITE, "terracotta_white");
        materialColors.put(MaterialColor.TERRACOTTA_YELLOW, "terracotta_yellow");
        materialColors.put(MaterialColor.WATER, "water");
        materialColors.put(MaterialColor.WARPED_HYPHAE, "warped_hyphae");
        materialColors.put(MaterialColor.WARPED_NYLIUM, "warped_nylium");
        materialColors.put(MaterialColor.WARPED_STEM, "warped_stem");
        materialColors.put(MaterialColor.WARPED_WART_BLOCK, "warped_wart");
        materialColors.put(MaterialColor.WOOD, "wood");
        materialColors.put(MaterialColor.WOOL, "wool");
    }
}
